### ISSUE TITLE
BottomNavigationBarItem title not visible

### ISSUE THREAD

**Issue by syntacops** [seel-channel/scroll_navigation#1]
Hello,

thank you for creating this nice package. It's working fine so far and it saves me lot of boilerplate.

However I'm wondering why the titles of the bottomNavigationBarItems are not visible. Please consider to implement this in a future update. 

![09-08-_2020_17-07-49](https://user-images.githubusercontent.com/68994521/89735474-0349b100-da63-11ea-951f-1dac51fdb83f.png)

Greetings
syntacops

**Comment by seel-channel** [comment]
I just solved the problem in version 1.0.2 of the package.
To activate the titles you need to enter: showNavItemsTitle: true.

**Comment by syntacops** [comment]
Great work! Thank you!
