### ISSUE TITLE
type 'AnimatedBuilder' is not a subtype of type 'PreferredSizeWidget?' in type cast

### ISSUE THREAD

**Issue by hengvenchang** [seel-channel/scroll_navigation#2]
Thank you for creating this wonderful widget, I'm trying to test but got this error
[
<img width="766" alt="Screen Shot 2021-03-11 at 5 56 31 PM" src="https://user-images.githubusercontent.com/17307495/110777036-4129e480-8293-11eb-9089-421aafba5ab2.png">
]

**Comment by seel-channel** [comment]
My mistake. In a little days I improved that widget

**Comment by hengvenchang** [comment]
Thank you Sir!

**Comment by seel-channel** [comment]
Done! The Screen Widget only recives the appBar and body, I have deleted the center, showAppBar, left, center and right widget. Please check the example and update to release 1.3.1
